### PR TITLE
Support of webp

### PR DESCRIPTION
**Pull request by MasterOfZozo**
Support of webp

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks, but this is not something we want by default. The defaults is for the common case and WebP is not a common case. You can easily use the imagemin-webp plugin yourself though ;)

**Comment by bre7** [comment]
Reopen ? WebP is actually pretty common nowadays.

**Comment by CcRaZyY** [comment]
Hi, maybe reopen?

**Comment by ialphan** [comment]
+1

**Comment by veronicamirada** [comment]
Please, consider reopening this. imagemin-webp is just to convert images to webp, but if you don't add .webp extension to validExts, webp images themselves are not optimized. It is just a small change. Thank you.

**Pull request closed without merging**
