### PR TITLE
add silent option

### PR DESCRIPTION
**Pull request by brillout**

### CODE REVIEW

**Comment by shinnn** [comment]
Duplicate: https://github.com/sindresorhus/gulp-imagemin/pull/14

**Comment by brillout** [comment]
I don't get this.

There is already a hacky solution because Gulp is lacking a proper logging system.

```js
		// TODO: remove this when gulp get's a real logger with levels
		verbose: process.argv.indexOf('--verbose') !== -1
```

How is adding a silent option different to these two lines?

I can add a `// TODO: remove this when gulp get's a real logger with levels` to the PR if that's the issue.

**Comment by shinnn** [comment]
@brillout At least you should check the closed PRs and issues before submitting this.

**Comment by brillout** [comment]
@shinnn Yes I should have checked the closed Issues, sorry about that.

**Pull request closed without merging**
